// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void   LVGL_knob_event(void *event) {}
void   LVGL_button_event(void *event) {}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_TeaScreen_screen_init();
    ui_TeapotScreen_screen_init();
    ui_BrewInfuseScreen_screen_init();
    ui_ErrorScreen_screen_init();
    ui_TeaPropertiesScreen_screen_init();
    ui_BrewNowOrSchedulerScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_SchedulerScreen_screen_init();
    ui_ScheduledScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}

void ui_destroy(void)
{
    ui_MainScreen_screen_destroy();
    ui_TeaScreen_screen_destroy();
    ui_TeapotScreen_screen_destroy();
    ui_BrewInfuseScreen_screen_destroy();
    ui_ErrorScreen_screen_destroy();
    ui_TeaPropertiesScreen_screen_destroy();
    ui_BrewNowOrSchedulerScreen_screen_destroy();
    ui_SettingsScreen_screen_destroy();
    ui_SchedulerScreen_screen_destroy();
    ui_ScheduledScreen_screen_destroy();
}
