// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_TeaScreen.h"
#include "screens/ui_TeapotScreen.h"
#include "screens/ui_BrewInfuseScreen.h"
#include "screens/ui_ErrorScreen.h"
#include "screens/ui_TeaPropertiesScreen.h"
#include "screens/ui_BrewNowOrSchedulerScreen.h"
#include "screens/ui_SettingsScreen.h"
#include "screens/ui_SchedulerScreen.h"
#include "screens/ui_ScheduledScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_title_png);    // assets/title.png
LV_IMG_DECLARE(ui_img_greenteascreen_png);    // assets/greenteascreen.png
LV_IMG_DECLARE(ui_img_191910993);    // assets/play-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_2046542749);    // assets/cookie-edit-outline-custom.png
LV_IMG_DECLARE(ui_img_teapot_png);    // assets/teapot.png
LV_IMG_DECLARE(ui_img_1134812263);    // assets/stop-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_287775719);    // assets/check-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_500202543);    // assets/close-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_726548789);    // assets/coffee-to-go-outline-custom.png
LV_IMG_DECLARE(ui_img_231652102);    // assets/clock-outline-custom.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
