// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"
#include "../uart_comm.h"

// Max tea types
#define MAX_TEA_TYPES 6

///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"
#include "screens/ui_TeaScreen.h"
#include "screens/ui_TeapotScreen.h"
#include "screens/ui_BrewInfuseScreen.h"
#include "screens/ui_ErrorScreen.h"
#include "screens/ui_TeaPropertiesScreen.h"
#include "screens/ui_BrewNowOrSchedulerScreen.h"
#include "screens/ui_SettingsScreen.h"
#include "screens/ui_SchedulerScreen.h"
#include "screens/ui_ScheduledScreen.h"

///////////////////// VARIABLES ////////////////////

// Screen tracking structure
typedef struct {
    uint8_t current_screen;
} ui_screen_state_t;

extern ui_screen_state_t ui_screen_state;

// Screen IDs
#define UI_SCREEN_MAIN 0
#define UI_SCREEN_TEA 1
#define UI_SCREEN_TEAPOT 2
#define UI_SCREEN_BREW_INFUSE 3
#define UI_SCREEN_ERROR 4
#define UI_SCREEN_TEA_PROPERTIES 5
#define UI_SCREEN_BREW_NOW_OR_SCHEDULER 6
#define UI_SCREEN_SETTINGS 7
#define UI_SCREEN_SCHEDULER 8
#define UI_SCREEN_SCHEDULED 9

// Tea colors array (extern declaration)
extern const uint32_t tea_colors[MAX_TEA_TYPES];

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_title_png);    // assets/title.png
LV_IMG_DECLARE(ui_img_greenteascreen_png);    // assets/greenteascreen.png
LV_IMG_DECLARE(ui_img_blackteascreen_png);    // assets/blackteascreen.png
LV_IMG_DECLARE(ui_img_herbalteascreen_png);    // assets/herbalteascreen.png
LV_IMG_DECLARE(ui_img_fruitteascreen_png);    // assets/fruitteascreen.png
LV_IMG_DECLARE(ui_img_whiteteascreen_png);    // assets/whiteteascreen.png
LV_IMG_DECLARE(ui_img_functionalteascreen_png);    // assets/functionalteascreen.png
LV_IMG_DECLARE(ui_img_191910993);    // assets/play-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_2046542749);    // assets/cookie-edit-outline-custom.png
LV_IMG_DECLARE(ui_img_teapot_png);    // assets/teapot.png
LV_IMG_DECLARE(ui_img_1134812263);    // assets/stop-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_287775719);    // assets/check-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_500202543);    // assets/close-circle-outline-custom.png
LV_IMG_DECLARE(ui_img_726548789);    // assets/coffee-to-go-outline-custom.png
LV_IMG_DECLARE(ui_img_231652102);    // assets/clock-outline-custom.png

///////////////////// HELPER FUNCTIONS ////////////////////

// Tea screen helpers
void update_tea_screen_label(void);
void update_tea_color(void);
void update_tea_background(void);

// Motor control helpers
void ui_motor_move_to_drying_position(int32_t position);

// Motor callbacks (called from app_main.c)
void ui_on_home_complete(bool success);
void ui_on_motor_status_update(const motor_status_t *status);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif