// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void checkPot(lv_event_t * e)
{
	// Your code here
}

void stopBrewing(lv_event_t * e)
{
	// Your code here
}

void nextTeaScreen(lv_event_t * e)
{
	// Your code here
}

void changeScreenToTeaPropertiesScreen(lv_event_t * e)
{
	// Your code here
}

void changeTeaTemperature(lv_event_t * e)
{
	// Your code here
}

void changeInfusionTimeSecond(lv_event_t * e)
{
	// Your code here
}

void changeInfusionTimeMinute(lv_event_t * e)
{
	// Your code here
}

void ReturnToTeaScreen(lv_event_t * e)
{
	// Your code here
}

void brewNow(lv_event_t * e)
{
	// Your code here
}

void startBrewing(lv_event_t * e)
{
	// Your code here
}

void changeBrewingTeaTemperature(lv_event_t * e)
{
	// Your code here
}

void changeDryingTime(lv_event_t * e)
{
	// Your code here
}

void dryingPositionUp(lv_event_t * e)
{
	// Your code here
}

void dryingPositionDown(lv_event_t * e)
{
	// Your code here
}

void changeSchedulerTemperature(lv_event_t * e)
{
	// Your code here
}

void changeSchedulerTimeMinute(lv_event_t * e)
{
	// Your code here
}

void changeSchedulerTimeHour(lv_event_t * e)
{
	// Your code here
}

void beginScheduler(lv_event_t * e)
{
	// Your code here
}

void stopScheduledBrew(lv_event_t * e)
{
	// Your code here
}

void onMainScreen(lv_event_t * e)
{
	// Your code here
}

void onTeaScreen(lv_event_t * e)
{
	// Your code here
}

void onTeapotScreen(lv_event_t * e)
{
	// Your code here
}

void onBrewInfuseScreen(lv_event_t * e)
{
	// Your code here
}

void onErrorScreen(lv_event_t * e)
{
	// Your code here
}

void onTeaPropertieScreen(lv_event_t * e)
{
	// Your code here
}

void onBrewNowOrSchedulerScreen(lv_event_t * e)
{
	// Your code here
}

void onSettingsScreen(lv_event_t * e)
{
	// Your code here
}

void onSchedulerScreen(lv_event_t * e)
{
	// Your code here
}

void onScheduledScreen(lv_event_t * e)
{
	// Your code here
}
