// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// Debug mode flag - set to 0 for production builds
#define DEBUG_ENABLED 0

// Global tea index for navigation
extern uint8_t current_tea_index;

// Initialize UI events - creates NVS save task
void ui_events_init(void);

// Process any pending schedule (called after motor homing)
void ui_events_process_pending_schedule(void);

// Start a scheduled brew
void ui_start_schedule_brew(uint8_t hour, uint8_t minute, uint8_t target_temp);

// Cancel a scheduled brew
void ui_cancel_schedule_brew(void);

// Startup motor initialization - home and move to idle position
void ui_startup_motor_init(void);

void onMainScreen(lv_event_t * e);
void nextTeaScreen(lv_event_t * e);
void onTeaScreen(lv_event_t * e);
void onTeapotScreen(lv_event_t * e);
void onBrewInfuseScreen(lv_event_t * e);
void stopBrewing(lv_event_t * e);
void onErrorScreen(lv_event_t * e);
void onTeaPropertieScreen(lv_event_t * e);
void changeBrewingTeaTemperature(lv_event_t * e);
void changeInfusionTimeSecond(lv_event_t * e);
void changeInfusionTimeMinute(lv_event_t * e);
void onBrewNowOrSchedulerScreen(lv_event_t * e);
void brewNow(lv_event_t * e);
void onSettingsScreen(lv_event_t * e);
void idlePositionUp(lv_event_t * e);
void idlePositionDown(lv_event_t * e);
void startTeabagDropoff(lv_event_t * e);
void onSchedulerScreen(lv_event_t * e);
void changeSchedulerTemperature(lv_event_t * e);
void changeSchedulerTimeMinute(lv_event_t * e);
void changeSchedulerTimeHour(lv_event_t * e);
void beginScheduler(lv_event_t * e);
void onScheduledScreen(lv_event_t * e);
void stopScheduledBrew(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif