// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

// Global tea index for navigation
extern uint8_t current_tea_index;

// Helper function for updating tea screen label
void update_tea_screen_label(void);
// Helper function for updating tea color theme
void update_tea_color(void);

void onMainScreen(lv_event_t * e);
void nextTeaScreen(lv_event_t * e);
void onTeaScreen(lv_event_t * e);
void onTeapotScreen(lv_event_t * e);
void onBrewInfuseScreen(lv_event_t * e);
void stopBrewing(lv_event_t * e);
void onErrorScreen(lv_event_t * e);
void onTeaPropertieScreen(lv_event_t * e);
void changeBrewingTeaTemperature(lv_event_t * e);
void changeInfusionTimeSecond(lv_event_t * e);
void changeInfusionTimeMinute(lv_event_t * e);
void onBrewNowOrSchedulerScreen(lv_event_t * e);
void brewNow(lv_event_t * e);
void onSettingsScreen(lv_event_t * e);
void changeDryingTime(lv_event_t * e);
void dryingPositionUp(lv_event_t * e);
void dryingPositionDown(lv_event_t * e);
void onSchedulerScreen(lv_event_t * e);
void changeSchedulerTemperature(lv_event_t * e);
void changeSchedulerTimeMinute(lv_event_t * e);
void changeSchedulerTimeHour(lv_event_t * e);
void beginScheduler(lv_event_t * e);
void onScheduledScreen(lv_event_t * e);
void stopScheduledBrew(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
