// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BREWNOWORSCHEDULERSCREEN_H
#define UI_BREWNOWORSCHEDULERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrewNowOrSchedulerScreen
extern void ui_BrewNowOrSchedulerScreen_screen_init(void);
extern void ui_BrewNowOrSchedulerScreen_screen_destroy(void);
extern void ui_event_BrewNowOrSchedulerScreen(lv_event_t * e);
extern lv_obj_t * ui_BrewNowOrSchedulerScreen;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label10;
extern void ui_event_ReturnToTeaScreen3(lv_event_t * e);
extern lv_obj_t * ui_ReturnToTeaScreen3;
extern void ui_event_BrewNow(lv_event_t * e);
extern lv_obj_t * ui_BrewNow;
extern void ui_event_Schedule(lv_event_t * e);
extern lv_obj_t * ui_Schedule;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

