// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_BrewInfuseScreen = NULL;
lv_obj_t * ui_StopBrewing = NULL;
lv_obj_t * ui_brewingArc = NULL;
lv_obj_t * ui_BrewInfuseTitle = NULL;
lv_obj_t * ui_BrewInfuseCurrentValue = NULL;
lv_obj_t * ui_BrewInfuseSetValue = NULL;
// event funtions
void ui_event_BrewInfuseScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onBrewInfuseScreen(e);
    }
}

void ui_event_StopBrewing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        stopBrewing(e);
    }
}

// build funtions

void ui_BrewInfuseScreen_screen_init(void)
{
    ui_BrewInfuseScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BrewInfuseScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BrewInfuseScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_BrewInfuseScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_StopBrewing = lv_button_create(ui_BrewInfuseScreen);
    lv_obj_set_width(ui_StopBrewing, 100);
    lv_obj_set_height(ui_StopBrewing, 100);
    lv_obj_set_x(ui_StopBrewing, 0);
    lv_obj_set_y(ui_StopBrewing, 139);
    lv_obj_set_align(ui_StopBrewing, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_StopBrewing, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_StopBrewing, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_StopBrewing, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_StopBrewing, &ui_img_1134812263, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_brewingArc = lv_arc_create(ui_BrewInfuseScreen);
    lv_obj_set_width(ui_brewingArc, 480);
    lv_obj_set_height(ui_brewingArc, 480);
    lv_obj_set_x(ui_brewingArc, 0);
    lv_obj_set_y(ui_brewingArc, -2);
    lv_obj_set_align(ui_brewingArc, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_brewingArc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_brewingArc, 43);
    lv_obj_set_style_pad_left(ui_brewingArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_brewingArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_brewingArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_brewingArc, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_brewingArc, lv_color_hex(0xC9C8B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_brewingArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_brewingArc, lv_color_hex(0xFF5B2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_brewingArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_brewingArc, lv_color_hex(0xFF5B2B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brewingArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BrewInfuseTitle = lv_label_create(ui_BrewInfuseScreen);
    lv_obj_set_width(ui_BrewInfuseTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewInfuseTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewInfuseTitle, 0);
    lv_obj_set_y(ui_BrewInfuseTitle, 60);
    lv_obj_set_align(ui_BrewInfuseTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_BrewInfuseTitle, "Brew");
    lv_obj_remove_flag(ui_BrewInfuseTitle,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_BrewInfuseTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewInfuseTitle, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewInfuseCurrentValue = lv_label_create(ui_BrewInfuseScreen);
    lv_obj_set_width(ui_BrewInfuseCurrentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewInfuseCurrentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewInfuseCurrentValue, 1);
    lv_obj_set_y(ui_BrewInfuseCurrentValue, -50);
    lv_obj_set_align(ui_BrewInfuseCurrentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewInfuseCurrentValue, "43 °C");
    lv_obj_set_style_text_align(ui_BrewInfuseCurrentValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewInfuseCurrentValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewInfuseSetValue = lv_label_create(ui_BrewInfuseScreen);
    lv_obj_set_width(ui_BrewInfuseSetValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrewInfuseSetValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrewInfuseSetValue, 1);
    lv_obj_set_y(ui_BrewInfuseSetValue, 8);
    lv_obj_set_align(ui_BrewInfuseSetValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrewInfuseSetValue, "100 °C");
    lv_obj_remove_flag(ui_BrewInfuseSetValue,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_BrewInfuseSetValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrewInfuseSetValue, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_StopBrewing, ui_event_StopBrewing, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewInfuseScreen, ui_event_BrewInfuseScreen, LV_EVENT_ALL, NULL);

}

void ui_BrewInfuseScreen_screen_destroy(void)
{
    if(ui_BrewInfuseScreen) lv_obj_del(ui_BrewInfuseScreen);

    // NULL screen variables
    ui_BrewInfuseScreen = NULL;
    ui_StopBrewing = NULL;
    ui_brewingArc = NULL;
    ui_BrewInfuseTitle = NULL;
    ui_BrewInfuseCurrentValue = NULL;
    ui_BrewInfuseSetValue = NULL;

}
