// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BREWINFUSESCREEN_H
#define UI_BREWINFUSESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrewInfuseScreen
extern void ui_BrewInfuseScreen_screen_init(void);
extern void ui_BrewInfuseScreen_screen_destroy(void);
extern void ui_event_BrewInfuseScreen(lv_event_t * e);
extern lv_obj_t * ui_BrewInfuseScreen;
extern void ui_event_StopBrewing(lv_event_t * e);
extern lv_obj_t * ui_StopBrewing;
extern lv_obj_t * ui_brewingArc;
extern lv_obj_t * ui_BrewInfuseTitle;
extern lv_obj_t * ui_BrewInfuseCurrentValue;
extern lv_obj_t * ui_BrewInfuseSetValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

