// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_BrewNowOrSchedulerScreen = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_ReturnToTeaScreen3 = NULL;
lv_obj_t * ui_BrewNow = NULL;
lv_obj_t * ui_Schedule = NULL;
// event funtions
void ui_event_BrewNowOrSchedulerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onBrewNowOrSchedulerScreen(e);
    }
}

void ui_event_ReturnToTeaScreen3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaScreen_screen_init);
    }
}

void ui_event_BrewNow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        brewNow(e);
    }
}

void ui_event_Schedule(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SchedulerScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_SchedulerScreen_screen_init);
    }
}

// build funtions

void ui_BrewNowOrSchedulerScreen_screen_init(void)
{
    ui_BrewNowOrSchedulerScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BrewNowOrSchedulerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BrewNowOrSchedulerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_BrewNowOrSchedulerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label11 = lv_label_create(ui_BrewNowOrSchedulerScreen);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, 80);
    lv_obj_set_align(ui_Label11, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label11, "Choose Brew Time");
    lv_obj_remove_flag(ui_Label11, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_BrewNowOrSchedulerScreen);
    lv_obj_set_width(ui_Label10, lv_pct(100));
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, 130);
    lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label10, "Do you want to brew your tea right now\nor schedule it for later?");
    lv_obj_remove_flag(ui_Label10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReturnToTeaScreen3 = lv_button_create(ui_BrewNowOrSchedulerScreen);
    lv_obj_set_width(ui_ReturnToTeaScreen3, 100);
    lv_obj_set_height(ui_ReturnToTeaScreen3, 100);
    lv_obj_set_x(ui_ReturnToTeaScreen3, 0);
    lv_obj_set_y(ui_ReturnToTeaScreen3, 139);
    lv_obj_set_align(ui_ReturnToTeaScreen3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReturnToTeaScreen3,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_ReturnToTeaScreen3, &ui_img_500202543, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrewNow = lv_button_create(ui_BrewNowOrSchedulerScreen);
    lv_obj_set_width(ui_BrewNow, 100);
    lv_obj_set_height(ui_BrewNow, 100);
    lv_obj_set_x(ui_BrewNow, -87);
    lv_obj_set_y(ui_BrewNow, 10);
    lv_obj_set_align(ui_BrewNow, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BrewNow, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_BrewNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_BrewNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_BrewNow, &ui_img_726548789, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schedule = lv_button_create(ui_BrewNowOrSchedulerScreen);
    lv_obj_set_width(ui_Schedule, 100);
    lv_obj_set_height(ui_Schedule, 100);
    lv_obj_set_x(ui_Schedule, 87);
    lv_obj_set_y(ui_Schedule, 10);
    lv_obj_set_align(ui_Schedule, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Schedule, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Schedule, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Schedule, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_Schedule, &ui_img_231652102, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ReturnToTeaScreen3, ui_event_ReturnToTeaScreen3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewNow, ui_event_BrewNow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Schedule, ui_event_Schedule, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrewNowOrSchedulerScreen, ui_event_BrewNowOrSchedulerScreen, LV_EVENT_ALL, NULL);

}

void ui_BrewNowOrSchedulerScreen_screen_destroy(void)
{
    if(ui_BrewNowOrSchedulerScreen) lv_obj_del(ui_BrewNowOrSchedulerScreen);

    // NULL screen variables
    ui_BrewNowOrSchedulerScreen = NULL;
    ui_Label11 = NULL;
    ui_Label10 = NULL;
    ui_ReturnToTeaScreen3 = NULL;
    ui_BrewNow = NULL;
    ui_Schedule = NULL;

}
