// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_ERRORSCREEN_H
#define UI_ERRORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ErrorScreen
extern void ui_ErrorScreen_screen_init(void);
extern void ui_ErrorScreen_screen_destroy(void);
extern lv_obj_t * ui_ErrorScreen;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_TextArea1;
extern void ui_event_ReturnToTeaScreen2(lv_event_t * e);
extern lv_obj_t * ui_ReturnToTeaScreen2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

