// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ErrorScreen = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_ReturnToTeaScreen2 = NULL;
// event funtions
void ui_event_ReturnToTeaScreen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaScreen_screen_init);
    }
}

// build funtions

void ui_ErrorScreen_screen_init(void)
{
    ui_ErrorScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ErrorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ErrorScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ErrorScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label6 = lv_label_create(ui_ErrorScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 60);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "Error occured");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_ErrorScreen);
    lv_obj_set_width(ui_TextArea1, 360);
    lv_obj_set_height(ui_TextArea1, 221);
    lv_obj_set_x(ui_TextArea1, 0);
    lv_obj_set_y(ui_TextArea1, -25);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "This specific error occured.");
    lv_obj_remove_flag(ui_TextArea1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ReturnToTeaScreen2 = lv_button_create(ui_ErrorScreen);
    lv_obj_set_width(ui_ReturnToTeaScreen2, 100);
    lv_obj_set_height(ui_ReturnToTeaScreen2, 100);
    lv_obj_set_x(ui_ReturnToTeaScreen2, 0);
    lv_obj_set_y(ui_ReturnToTeaScreen2, 139);
    lv_obj_set_align(ui_ReturnToTeaScreen2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReturnToTeaScreen2,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_ReturnToTeaScreen2, &ui_img_287775719, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ReturnToTeaScreen2, ui_event_ReturnToTeaScreen2, LV_EVENT_ALL, NULL);

}

void ui_ErrorScreen_screen_destroy(void)
{
    if(ui_ErrorScreen) lv_obj_del(ui_ErrorScreen);

    // NULL screen variables
    ui_ErrorScreen = NULL;
    ui_Label6 = NULL;
    ui_TextArea1 = NULL;
    ui_ReturnToTeaScreen2 = NULL;

}
