// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCHEDULEDSCREEN_H
#define UI_SCHEDULEDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScheduledScreen
extern void ui_ScheduledScreen_screen_init(void);
extern void ui_ScheduledScreen_screen_destroy(void);
extern lv_obj_t * ui_ScheduledScreen;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label33;
extern void ui_event_ReturnToTeaScreen6(lv_event_t * e);
extern lv_obj_t * ui_ReturnToTeaScreen6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

