// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCHEDULERSCREEN_H
#define UI_SCHEDULERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SchedulerScreen
extern void ui_SchedulerScreen_screen_init(void);
extern void ui_SchedulerScreen_screen_destroy(void);
extern lv_obj_t * ui_SchedulerScreen;
extern lv_obj_t * ui_Label20;
extern void ui_event_ReturnToTeaScreen4(lv_event_t * e);
extern lv_obj_t * ui_ReturnToTeaScreen4;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern void ui_event_Roller6(lv_event_t * e);
extern lv_obj_t * ui_Roller6;
extern lv_obj_t * ui_Label23;
extern void ui_event_Roller7(lv_event_t * e);
extern lv_obj_t * ui_Roller7;
extern void ui_event_Roller8(lv_event_t * e);
extern lv_obj_t * ui_Roller8;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern void ui_event_ReturnToTeaScreen5(lv_event_t * e);
extern lv_obj_t * ui_ReturnToTeaScreen5;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label26;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

