// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "../ui_events.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label18 = NULL;
#if DEBUG_ENABLED
lv_obj_t * ui_DebugButton = NULL;
lv_obj_t * ui_DebugLabel = NULL;
#endif
// event funtions
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        nextTeaScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onSettingsScreen(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        idlePositionUp(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        idlePositionDown(e);
    }
}

#if DEBUG_ENABLED
void ui_event_DebugButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        startTeabagDropoff(e);
    }
}
#endif

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SettingsScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SettingsScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label13 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 60);
    lv_obj_set_align(ui_Label13, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label13, "Settings");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -80);
    lv_obj_set_y(ui_Label15, -30);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Idle Position");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Button2, 50);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 115);
    lv_obj_set_y(ui_Button2, -30);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Label17 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 115);
    lv_obj_set_y(ui_Label17, -30);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "+");
    lv_obj_remove_flag(ui_Label17, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Button1, 50);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 185);
    lv_obj_set_y(ui_Button1, -30);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Label18 = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 185);
    lv_obj_set_y(ui_Label18, -32);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "-");
    lv_obj_remove_flag(ui_Label18, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

#if DEBUG_ENABLED
    // Debug button for teabag dropoff test
    ui_DebugButton = lv_button_create(ui_SettingsScreen);
    lv_obj_set_width(ui_DebugButton, 200);
    lv_obj_set_height(ui_DebugButton, 50);
    lv_obj_set_x(ui_DebugButton, 0);
    lv_obj_set_y(ui_DebugButton, 60);
    lv_obj_set_align(ui_DebugButton, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DebugButton, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_DebugButton, lv_color_hex(0xFF6600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DebugButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugLabel = lv_label_create(ui_DebugButton);
    lv_obj_set_width(ui_DebugLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_DebugLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_DebugLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DebugLabel, "Teabag Dropoff");
    lv_obj_set_style_text_font(ui_DebugLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DebugButton, ui_event_DebugButton, LV_EVENT_ALL, NULL);
#endif

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_Label13 = NULL;
    ui_Label15 = NULL;
    ui_Button2 = NULL;
    ui_Label17 = NULL;
    ui_Button1 = NULL;
    ui_Label18 = NULL;
#if DEBUG_ENABLED
    ui_DebugButton = NULL;
    ui_DebugLabel = NULL;
#endif

}
