// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScheduledScreen = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_ReturnToTeaScreen6 = NULL;
// event funtions
void ui_event_ScheduledScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onScheduledScreen(e);
    }
}

void ui_event_ReturnToTeaScreen6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaScreen_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        stopScheduledBrew(e);
    }
}

// build funtions

void ui_ScheduledScreen_screen_init(void)
{
    ui_ScheduledScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScheduledScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ScheduledScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_ScheduledScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label28 = lv_label_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, 60);
    lv_obj_set_align(ui_Label28, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label28, "Scheduled");
    lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 120);
    lv_obj_set_y(ui_Label30, -40);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "95 °C");
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 70);
    lv_obj_set_y(ui_Label31, 40);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "06:00");
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, 110);
    lv_obj_set_align(ui_Label29, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label29, "Tea brewing has begun.");

    ui_Label32 = lv_label_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label32, -65);
    lv_obj_set_y(ui_Label32, -40);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "The tea will reach a temperature of ");

    ui_Label33 = lv_label_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -40);
    lv_obj_set_y(ui_Label33, 40);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "at the time of ");

    ui_ReturnToTeaScreen6 = lv_button_create(ui_ScheduledScreen);
    lv_obj_set_width(ui_ReturnToTeaScreen6, 100);
    lv_obj_set_height(ui_ReturnToTeaScreen6, 100);
    lv_obj_set_x(ui_ReturnToTeaScreen6, 0);
    lv_obj_set_y(ui_ReturnToTeaScreen6, 139);
    lv_obj_set_align(ui_ReturnToTeaScreen6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReturnToTeaScreen6,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_ReturnToTeaScreen6, &ui_img_500202543, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ReturnToTeaScreen6, ui_event_ReturnToTeaScreen6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScheduledScreen, ui_event_ScheduledScreen, LV_EVENT_ALL, NULL);

}

void ui_ScheduledScreen_screen_destroy(void)
{
    if(ui_ScheduledScreen) lv_obj_del(ui_ScheduledScreen);

    // NULL screen variables
    ui_ScheduledScreen = NULL;
    ui_Label28 = NULL;
    ui_Label30 = NULL;
    ui_Label31 = NULL;
    ui_Label29 = NULL;
    ui_Label32 = NULL;
    ui_Label33 = NULL;
    ui_ReturnToTeaScreen6 = NULL;

}
