// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_SchedulerScreen = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_ReturnToTeaScreen4 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Roller6 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Roller7 = NULL;
lv_obj_t * ui_Roller8 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_ReturnToTeaScreen5 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label26 = NULL;
// event funtions
void ui_event_ReturnToTeaScreen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaScreen_screen_init);
    }
}

void ui_event_Roller6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeSchedulerTemperature(e);
    }
}

void ui_event_Roller7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeSchedulerTimeMinute(e);
    }
}

void ui_event_Roller8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeSchedulerTimeHour(e);
    }
}

void ui_event_ReturnToTeaScreen5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        beginScheduler(e);
    }
}

// build funtions

void ui_SchedulerScreen_screen_init(void)
{
    ui_SchedulerScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SchedulerScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SchedulerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_SchedulerScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label20 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 60);
    lv_obj_set_align(ui_Label20, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label20, "Scheduler");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReturnToTeaScreen4 = lv_button_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_ReturnToTeaScreen4, 100);
    lv_obj_set_height(ui_ReturnToTeaScreen4, 100);
    lv_obj_set_x(ui_ReturnToTeaScreen4, 80);
    lv_obj_set_y(ui_ReturnToTeaScreen4, 139);
    lv_obj_set_align(ui_ReturnToTeaScreen4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReturnToTeaScreen4,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_ReturnToTeaScreen4, &ui_img_500202543, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -80);
    lv_obj_set_y(ui_Label21, -80);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Temperature");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -80);
    lv_obj_set_y(ui_Label22, 20);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Target Time");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller6 = lv_roller_create(ui_SchedulerScreen);
    lv_roller_set_options(ui_Roller6, "25\n30\n35\n40\n45\n50\n55\n60\n65\n70\n75\n80\n85\n90\n95\n100",
                          LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller6, 5, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller6, 75);
    lv_obj_set_width(ui_Roller6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller6, -85);
    lv_obj_set_y(ui_Roller6, -80);
    lv_obj_set_align(ui_Roller6, LV_ALIGN_RIGHT_MID);

    ui_object_set_themeable_style_property(ui_Roller6, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Roller6, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Label23 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 182);
    lv_obj_set_y(ui_Label23, -72);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "°C");
    lv_obj_remove_flag(ui_Label23, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller7 = lv_roller_create(ui_SchedulerScreen);
    lv_roller_set_options(ui_Roller7,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller7, 75);
    lv_obj_set_width(ui_Roller7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller7, 156);
    lv_obj_set_y(ui_Roller7, 20);
    lv_obj_set_align(ui_Roller7, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Roller7, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Roller7, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Roller8 = lv_roller_create(ui_SchedulerScreen);
    lv_roller_set_options(ui_Roller8,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller8, 6, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller8, 75);
    lv_obj_set_width(ui_Roller8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller8, 95);
    lv_obj_set_y(ui_Roller8, 20);
    lv_obj_set_align(ui_Roller8, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Roller8, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Roller8, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Label24 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 95);
    lv_obj_set_y(ui_Label24, 71);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "h");
    lv_obj_remove_flag(ui_Label24, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 156);
    lv_obj_set_y(ui_Label25, 71);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "m");
    lv_obj_remove_flag(ui_Label25, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReturnToTeaScreen5 = lv_button_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_ReturnToTeaScreen5, 100);
    lv_obj_set_height(ui_ReturnToTeaScreen5, 100);
    lv_obj_set_x(ui_ReturnToTeaScreen5, -80);
    lv_obj_set_y(ui_ReturnToTeaScreen5, 139);
    lv_obj_set_align(ui_ReturnToTeaScreen5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReturnToTeaScreen5,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_ReturnToTeaScreen5, &ui_img_287775719, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 125);
    lv_obj_set_y(ui_Label19, 20);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, ":");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_SchedulerScreen);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -80);
    lv_obj_set_y(ui_Label26, -80);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Temperature");
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ReturnToTeaScreen4, ui_event_ReturnToTeaScreen4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller6, ui_event_Roller6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller7, ui_event_Roller7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller8, ui_event_Roller8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ReturnToTeaScreen5, ui_event_ReturnToTeaScreen5, LV_EVENT_ALL, NULL);

}

void ui_SchedulerScreen_screen_destroy(void)
{
    if(ui_SchedulerScreen) lv_obj_del(ui_SchedulerScreen);

    // NULL screen variables
    ui_SchedulerScreen = NULL;
    ui_Label20 = NULL;
    ui_ReturnToTeaScreen4 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_Roller6 = NULL;
    ui_Label23 = NULL;
    ui_Roller7 = NULL;
    ui_Roller8 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_ReturnToTeaScreen5 = NULL;
    ui_Label19 = NULL;
    ui_Label26 = NULL;

}
