// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_TeaName;
lv_obj_t * uic_Begin;
lv_obj_t * ui_TeaScreen = NULL;
lv_obj_t * ui_Begin = NULL;
lv_obj_t * ui_TeaName = NULL;
lv_obj_t * ui_Edit = NULL;
// event funtions
void ui_event_TeaScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        nextTeaScreen(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onTeaScreen(e);
    }
}

void ui_event_Begin(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrewNowOrSchedulerScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_BrewNowOrSchedulerScreen_screen_init);
    }
}

void ui_event_Edit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaPropertiesScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaPropertiesScreen_screen_init);
    }
}

// build funtions

void ui_TeaScreen_screen_init(void)
{
    ui_TeaScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TeaScreen, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    ui_object_set_themeable_style_property(ui_TeaScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_TeaScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);
    lv_obj_set_style_bg_image_src(ui_TeaScreen, &ui_img_greenteascreen_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Begin = lv_button_create(ui_TeaScreen);
    lv_obj_set_width(ui_Begin, 100);
    lv_obj_set_height(ui_Begin, 100);
    lv_obj_set_x(ui_Begin, -87);
    lv_obj_set_y(ui_Begin, 139);
    lv_obj_set_align(ui_Begin, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Begin, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Begin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Begin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_Begin, &ui_img_191910993, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TeaName = lv_label_create(ui_TeaScreen);
    lv_obj_set_width(ui_TeaName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TeaName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TeaName, 0);
    lv_obj_set_y(ui_TeaName, 50);
    lv_obj_set_align(ui_TeaName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TeaName, "Green Tea");
    lv_obj_remove_flag(ui_TeaName, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_TeaName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TeaName, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Edit = lv_button_create(ui_TeaScreen);
    lv_obj_set_width(ui_Edit, 100);
    lv_obj_set_height(ui_Edit, 100);
    lv_obj_set_x(ui_Edit, 87);
    lv_obj_set_y(ui_Edit, 139);
    lv_obj_set_align(ui_Edit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Edit, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_Edit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Edit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_Edit, &ui_img_2046542749, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Begin, ui_event_Begin, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Edit, ui_event_Edit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TeaScreen, ui_event_TeaScreen, LV_EVENT_ALL, NULL);
    uic_Begin = ui_Begin;
    uic_TeaName = ui_TeaName;

}

void ui_TeaScreen_screen_destroy(void)
{
    if(ui_TeaScreen) lv_obj_del(ui_TeaScreen);

    // NULL screen variables
    ui_TeaScreen = NULL;
    uic_Begin = NULL;
    ui_Begin = NULL;
    uic_TeaName = NULL;
    ui_TeaName = NULL;
    ui_Edit = NULL;

}
