// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_TEAPOTSCREEN_H
#define UI_TEAPOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TeapotScreen
extern void ui_TeapotScreen_screen_init(void);
extern void ui_TeapotScreen_screen_destroy(void);
extern lv_obj_t * ui_TeapotScreen;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

