// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_TEAPROPERTIESSCREEN_H
#define UI_TEAPROPERTIESSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TeaPropertiesScreen
extern void ui_TeaPropertiesScreen_screen_init(void);
extern void ui_TeaPropertiesScreen_screen_destroy(void);
extern void ui_event_TeaPropertiesScreen(lv_event_t * e);
extern lv_obj_t * ui_TeaPropertiesScreen;
extern lv_obj_t * ui_Label5;
extern void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label7;
extern void ui_event_Roller4(lv_event_t * e);
extern lv_obj_t * ui_Roller4;
extern void ui_event_Roller2(lv_event_t * e);
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern void ui_event_ReturnToTeaScreen(lv_event_t * e);
extern lv_obj_t * ui_ReturnToTeaScreen;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label27;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

