// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_TeaPropertiesScreen = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Roller1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Roller4 = NULL;
lv_obj_t * ui_Roller2 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_ReturnToTeaScreen = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label27 = NULL;
// event funtions
void ui_event_Roller1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeBrewingTeaTemperature(e);
    }
}

void ui_event_Roller4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeInfusionTimeSecond(e);
    }
}

void ui_event_Roller2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        changeInfusionTimeMinute(e);
    }
}

void ui_event_ReturnToTeaScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TeaScreen, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_TeaScreen_screen_init);
    }
}

// build funtions

void ui_TeaPropertiesScreen_screen_init(void)
{
    ui_TeaPropertiesScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TeaPropertiesScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TeaPropertiesScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_TeaPropertiesScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label5 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 60);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "Tea Properties");
    lv_obj_remove_flag(ui_Label5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_TeaPropertiesScreen);
    lv_roller_set_options(ui_Roller1, "75\n80\n85\n90\n95\n100", LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller1, 5, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller1, 75);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller1, -85);
    lv_obj_set_y(ui_Roller1, -80);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_RIGHT_MID);

    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Roller1, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Label3 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -80);
    lv_obj_set_y(ui_Label3, -80);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Temperature");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -80);
    lv_obj_set_y(ui_Label7, 20);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Infusion Time");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller4 = lv_roller_create(ui_TeaPropertiesScreen);
    lv_roller_set_options(ui_Roller4,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller4, 75);
    lv_obj_set_width(ui_Roller4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller4, 156);
    lv_obj_set_y(ui_Roller4, 20);
    lv_obj_set_align(ui_Roller4, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Roller4, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Roller4, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Roller2 = lv_roller_create(ui_TeaPropertiesScreen);
    lv_roller_set_options(ui_Roller2, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14",
                          LV_ROLLER_MODE_INFINITE);
    lv_roller_set_selected(ui_Roller2, 3, LV_ANIM_OFF);
    lv_obj_set_height(ui_Roller2, 75);
    lv_obj_set_width(ui_Roller2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller2, 95);
    lv_obj_set_y(ui_Roller2, 20);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);

    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_Roller2, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);

    ui_Label8 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 95);
    lv_obj_set_y(ui_Label8, 71);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "m");
    lv_obj_remove_flag(ui_Label8, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 155);
    lv_obj_set_y(ui_Label9, 71);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "s");
    lv_obj_remove_flag(ui_Label9, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReturnToTeaScreen = lv_button_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_ReturnToTeaScreen, 100);
    lv_obj_set_height(ui_ReturnToTeaScreen, 100);
    lv_obj_set_x(ui_ReturnToTeaScreen, 0);
    lv_obj_set_y(ui_ReturnToTeaScreen, 139);
    lv_obj_set_align(ui_ReturnToTeaScreen, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReturnToTeaScreen,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_teacolor);
    ui_object_set_themeable_style_property(ui_ReturnToTeaScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_teacolor);
    lv_obj_set_style_bg_image_src(ui_ReturnToTeaScreen, &ui_img_287775719, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 182);
    lv_obj_set_y(ui_Label12, -72);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "°C");
    lv_obj_remove_flag(ui_Label12, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_TeaPropertiesScreen);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 125);
    lv_obj_set_y(ui_Label27, 20);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, ":");
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller4, ui_event_Roller4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Roller2, ui_event_Roller2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ReturnToTeaScreen, ui_event_ReturnToTeaScreen, LV_EVENT_ALL, NULL);

}

void ui_TeaPropertiesScreen_screen_destroy(void)
{
    if(ui_TeaPropertiesScreen) lv_obj_del(ui_TeaPropertiesScreen);

    // NULL screen variables
    ui_TeaPropertiesScreen = NULL;
    ui_Label5 = NULL;
    ui_Roller1 = NULL;
    ui_Label3 = NULL;
    ui_Label7 = NULL;
    ui_Roller4 = NULL;
    ui_Roller2 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_ReturnToTeaScreen = NULL;
    ui_Label12 = NULL;
    ui_Label27 = NULL;

}
