// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_TEASCREEN_H
#define UI_TEASCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TeaScreen
extern void ui_TeaScreen_screen_init(void);
extern void ui_TeaScreen_screen_destroy(void);
extern void ui_event_TeaScreen(lv_event_t * e);
extern lv_obj_t * ui_TeaScreen;
extern void ui_event_Begin(lv_event_t * e);
extern lv_obj_t * ui_Begin;
extern lv_obj_t * ui_TeaName;
extern void ui_event_Edit(lv_event_t * e);
extern lv_obj_t * ui_Edit;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Begin;
extern lv_obj_t * uic_TeaName;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

