// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_TeapotScreen = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Image6 = NULL;
// event funtions
void ui_event_TeapotScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        onTeapotScreen(e);
    }
}

// build funtions

void ui_TeapotScreen_screen_init(void)
{
    ui_TeapotScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TeapotScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TeapotScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_background);
    ui_object_set_themeable_style_property(ui_TeapotScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_background);

    ui_Label4 = lv_label_create(ui_TeapotScreen);
    lv_obj_set_width(ui_Label4, 368);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 65);
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "Place the teapot with water onto the marked area");
    lv_obj_remove_flag(ui_Label4, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Label4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_image_create(ui_TeapotScreen);
    lv_image_set_src(ui_Image6, &ui_img_teapot_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 206
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 273
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -10);
    lv_obj_set_align(ui_Image6, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    lv_obj_add_event_cb(ui_TeapotScreen, ui_event_TeapotScreen, LV_EVENT_ALL, NULL);

}

void ui_TeapotScreen_screen_destroy(void)
{
    if(ui_TeapotScreen) lv_obj_del(ui_TeapotScreen);

    // NULL screen variables
    ui_TeapotScreen = NULL;
    ui_Label4 = NULL;
    ui_Image6 = NULL;

}
