// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"
#include "iot_knob.h"
#include "iot_button.h"
static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
uint8_t HF_ui_screen_id=1;//Current Screen Index 1 Main Interface 2 Set Time 3 Work
uint8_t HF_open=0;
extern  int selected_index;
extern  char * options[];
extern  char * options2[];
extern int options_max_num;
extern int HF_number;

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
void ui_event_background(lv_event_t * e);
lv_obj_t * ui_background;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
// CUSTOM VARIABLES


// SCREEN: ui_time
void ui_time_screen_init(void);
void ui_event_time(lv_event_t * e);
lv_obj_t * ui_time;
lv_obj_t * ui_Roller1;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES


// SCREEN: ui_working
void ui_working_screen_init(void);
lv_obj_t * ui_working;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Bar1;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_back[1] = {&ui_img_back480_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

static int8_t index2=0;

static uint8_t HF_index=1;


//********************************* */
void   LVGL_knob_event(void *event)
{

    ESP_LOGI(TAG, "HF---Read  %d",event);
    if(event==KNOB_LEFT)
    {

       ESP_LOGI(TAG,"KNOB_LEFT");
       HF_index=1;
       if(HF_ui_screen_id==1)
       {
       index2++;
       if(index2>=7)//Only 6 images
       index2=1;
       }
        else if(HF_ui_screen_id==2)
       {
            selected_index++;
            if(selected_index>options_max_num)
                 selected_index=0;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);//The knob drives the pulley to rotate.
        }


    }
    else if(event==KNOB_RIGHT)
    {
        ESP_LOGI(TAG,"KNOB_RIGHT");
        HF_index=1;
        if(HF_ui_screen_id==1)
        {
        index2--;
        if(index2<=0)
        index2=5;
        }
         else if(HF_ui_screen_id==2)
       {
            selected_index--;
            if(selected_index<0)
                 selected_index=options_max_num;
            lv_roller_set_selected(ui_Roller1,selected_index,LV_ANIM_ON);//The knob drives the pulley to rotate.
        }
       
    }
    //  if(HF_index==1)
    // {

    //     HF_index=0;

        
    //     if(index2==1)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
    //     else if(index2==2)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
    //     else if(index2==3)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
    //     else if(index2==4)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
    //     else if(index2==5)
    //     _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
    //     else if(index2==6)
    //     {
           
    //         _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
    //     }
       
   
    // }

}
void   LVGL_button_event(void *event)
{
    static uint8_t last_event=BUTTON_PRESS_DOWN;
    ESP_LOGI(TAG, "HF---Read  %d",event);
    if(event==BUTTON_PRESS_DOWN)
    {
         ESP_LOGI(TAG,"BUTTON_PRESS_DOWN");
         

    }
    if(event==BUTTON_LONG_PRESS_HOLD)
    {
        if(HF_ui_screen_id==1)
        {
            HF_ui_screen_id=2;
            HF_index=0;
            last_event=BUTTON_LONG_PRESS_HOLD;
            _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);

            return;
        }
    }

     if(event==BUTTON_PRESS_UP)
    {
        ESP_LOGI(TAG,"BUTTON_PRESS_UP");
        if(last_event==BUTTON_LONG_PRESS_HOLD)
        {
           last_event=BUTTON_PRESS_DOWN;
           return ;
        }
        else{
                
            if(HF_ui_screen_id==1)
            {
                HF_ui_screen_id=3;
                HF_open=1;
                _ui_screen_change(&ui_working, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
            }
            else if(HF_ui_screen_id==2)
            {
                
                selected_index = lv_roller_get_selected(ui_Roller1); // 获取当前选中的索引  
                ESP_LOGE(TAG, "ui_Roller1 ==%d",selected_index);
                _ui_label_set_property(ui_Label3, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
                HF_ui_screen_id=1;
                _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);

            }
            else if(HF_ui_screen_id==3)
            {
                HF_ui_screen_id=1;
                HF_open=0;
                _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
            }

        }
      
    }
}


//************************* */
//After upgrading to LVGL v9, the knob event handler freezes after just a couple of rotations. Unbelievable.
void my_timer1(lv_timer_t * timer)
{
         if(HF_index==1)
    {

        HF_index=0;

        
        if(index2==1)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==2)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==3)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==4)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==5)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
        else if(index2==6)
        {
           
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        }
       
   
    }
}
///////////////////// FUNCTIONS ////////////////////
void ui_event_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        if(event_code == LV_EVENT_CLICKED) {//触摸点击
        index2++;
        if(index2>=7)
            index2=1;
        if(index2==1)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_2kaoji_png);
        else if(index2==2)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_3danta_png);
        else if(index2==3)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_4pisa_png);
        else if(index2==4)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_5liupai_png);
        else if(index2==5)
        _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_6shutiao_png);
        else if(index2==6)
        {
           
            _ui_image_set_property(ui_background, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_1kaorou_png);
        }
    }
       
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
         HF_ui_screen_id=3;
          HF_open=1;
        _ui_screen_change(&ui_working, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_working_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
          HF_ui_screen_id=2;
        _ui_screen_change(&ui_time, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_time_screen_init);
    }
}

void ui_event_time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
         HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
          HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
            selected_index = lv_roller_get_selected(ui_Roller1); // 获取当前选中的索引  
        HF_number= options2[selected_index];
        HF_ui_screen_id=1;
        _ui_label_set_property(ui_Label3, _UI_LABEL_PROPERTY_TEXT, options[selected_index]);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
           HF_ui_screen_id=1;
          HF_open=0;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 5, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_time_screen_init();
    ui_working_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
